/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "sg-contest"

include(":sg-contest-2016:sg-contest-2016-exercise-1")
include(":sg-contest-2016:sg-contest-2016-exercise-2")
include(":sg-contest-2016:sg-contest-2016-exercise-3")
include(":sg-contest-2016:sg-contest-2016-exercise-4")
include(":sg-contest-2016:sg-contest-2016-exercise-5")
include(":sg-contest-2016:sg-contest-2016-exercise-6")

include(":sg-contest-2017:sg-contest-2017-exercise-1")
include(":sg-contest-2017:sg-contest-2017-exercise-2")
include(":sg-contest-2017:sg-contest-2017-exercise-3")
include(":sg-contest-2017:sg-contest-2017-exercise-4")
include(":sg-contest-2017:sg-contest-2017-exercise-5")
include(":sg-contest-2017:sg-contest-2017-exercise-6")
